### ISSUE TITLE
Make JDBC table manager configurable to support drivers without prepared statement

### ISSUE THREAD

**Issue by brian-rickman** [prestodb/tempto#118]
It would be useful to have a table manager for Presto that does not depend on HDFS and Hive.  This will require loading data via individual INSERT statements.  Obviously performance will be poor, but for very small tables it should be acceptable.

**Comment by maciejgrzybek** [comment]
Just to clarify, this bug occurs while using Presto as a JDBC target in .ddl file.
Setup to reproduce:
[tempto-configuration.yaml](https://github.com/prestodb/tempto/files/212823/tempto-configuration.yaml.txt)
[datatype.ddl](https://github.com/prestodb/tempto/files/212825/datatype.ddl.txt)
[select01.sql](https://github.com/prestodb/tempto/files/212829/select01.sql.txt)

It does not work because Presto JDBC driver does not support batch inserts and prepared statements.
There is an exception thrown during execution of convention based tests:
`com.facebook.presto.jdbc.NotImplementedException: Method Connection.prepareStatement is not yet implemented`
