### ISSUE TITLE
Unable to specify database schema in tempto

### ISSUE THREAD

**Issue by rschlussel** [prestodb/tempto#76]
Currently the only way to specify a schema to use is to append it to the jdbc url in the configuration file.   This means that you need to define a different database for each schema that you want to use for a given connection.  It would be useful if in the functions to create and access tables you could specify the schema to create tables in for when you don't want to use the default.

**Comment by kokosing** [comment]
This is would be a big change in presto. Currently tables are accessed by its name (or table name and table database). There is no notion of schema. Now it would requires to pass schema to know where this table is created. So tempto would end up with similar design as presto has. In order to access a table you need to know database.schema.name. It is a breaking change, causing a need for a lot of existing product tests to be refactored.

Anyway I am working on it...

**Comment by rschlussel** [comment]
Thank you! I had been thinking that if you could make specifying the schema optional, then it shouldn't affect any existing product tests.  But you are more familiar with the code than I.
